### ISSUE TITLE
No more compatible with new HA release of June !

### ISSUE THREAD

**Issue by vincegre** [angelnu/home_assistant_thethingsnetwork#27]
Hi

After having upgraded HA to release 2025.6, integration is no more able to load properly and fails to start.

I attach logs when I try to reload integration.

Thanks

Vincèn

[home-assistant_thethingsnetwork_2025-06-12T10-44-12.619Z.log](https://github.com/user-attachments/files/20707347/home-assistant_thethingsnetwork_2025-06-12T10-44-12.619Z.log)

**Comment by angelnu** [comment]
Thanks for reporting. It is due to the async_forward_entry_setup renaming to async_forward_entry_setups. If it is just that it should be simple to fix

**Comment by gblanchet** [comment]
It is fixed ??
Gerard

**Comment by pingi27** [comment]
I got the same error:
```
Error setting up entry pingimytemptest for thethingsnetwork
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thethingsnetwork/__init__.py", line 61, in async_setup_entry
    await client.connect()
  File "/config/custom_components/thethingsnetwork/TTN_client.py", line 147, in connect
    self.__hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

But in addition the following error:

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/thethingsnetwork/TTN_client.py", line 277, in __update_listener
    return await TTN_client.getInstance(entry).__update(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thethingsnetwork/TTN_client.py", line 291, in __update
    await self.__coordinator.async_request_refresh()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'async_request_refresh'
```
Is this an other problem or a subsequent error?

Ekkart

**Comment by vmayoralb** [comment]
Hello,

i've rename the lines hass.config_entries.async_forward_entry_setup to hass.config_entries.async_forward_entry_setups in the files:

TTN_client.py
__init__.py

now the integration it's working but the entities are still not available

Thank you

**Comment by vincegre** [comment]
Any chance of a fix soon ? or better to switch back at official integration ?
Thanks

**Comment by vmayoralb** [comment]
Hi @vincegre. Could you let me know how to switch to the official integration? Just to try. I only find this integration
Thanks

**Comment by vincegre** [comment]
> Hi [@vincegre](https://github.com/vincegre). Could you let me know how to switch to the official integration? Just to try. I only find this integration Thanks

You remove the integration from the Integration panel in HA, then delete the folder of the custom integration and reboot and then you can activate the official integration. But the best way is to not use any integration at all and do through MQTT bridge (I use that already for some of my LoRa devices and going to switch the other ones, as that method works since years without any problems ;)

**Comment by angelnu** [comment]
I thought this has been reported on the official home-assistant x-)

Indeed, this custom integration is deprecated and the official one should be used. It does not have all the features yet but it benefits from being maintained in sync with the core.

Using MQTT is another option as indicated in the documentation - it has other limitations though.
